version: '3'
services:
  payment-service:
    image: wobline/payments:1.0.0
    build:
      context: ../
      dockerfile: ./development/Dockerfile
    container_name: payment-service
    network_mode: host
    depends_on:
      - postgresdb
      - cassandra
    ports:
      - "8080:8080"

  postgresdb:
    container_name: postgresdb
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./create_journal_and_snapshot_tables.sql:/docker-entrypoint-initdb.d/akka.sql
    ports:
      - "5432:5432"
    networks:
      - wobline-net

  cassandra:
    image: cassandra:3.11.11
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    networks:
      - wobline-net

networks:
  wobline-net:
    driver: bridge